$schema: http://json-schema.org/draft-07/schema#
type: object
properties:
  config:
    type: object
    properties:
      active:
        type: string
        description: 激活的配置环境
      name:
        type: string
        description: 定义的环境名称, 选取激活环境时的索引
      shared:
        type: boolean
        default: false
        description: 是否为共享的配置
